#ifndef IMU_REGISTERS_H
#define IMU_REGISTERS_H

#define IMU_SELF_TEST_X_GYRO 0x00
#define IMU_SELF_TEST_Y_GYRO 0x01
#define IMU_SELF_TEST_Z_GYRO 0x02

#define IMU_SELF_TEST_X_ACCEL 0x0D
#define IMU_SELF_TEST_Y_ACCEL 0x0E
#define IMU_SELF_TEST_Z_ACCEL 0x0F

#define IMU_SELF_TEST_A 0x10

#define IMU_SMPLRT_DIV 0x19
#define IMU_CONFIG 0x1A
#define IMU_GYRO_CONFIG 0x1B
#define IMU_ACCEL_CONFIG 0x1C
#define IMU_ACCEL_CONFIG2 0x1D
#define IMU_LP_ACCEL_ODR 0x1E
#define IMU_WOM_THR 0x1F

#define IMU_MOT_DUR 0x20
#define IMU_ZMOT_THR 0x21
#define IMU_ZRMOT_DUR 0x22

#define IMU_FIFO_EN 0x23
#define IMU_INT_PIN_CFG 0x37
#define IMU_INT_ENABLE 0x38
#define IMU_DMP_INT_STATUS 0x39
#define IMU_INT_STATUS 0x3A
#define IMU_ACCEL_XOUT_H 0x3B
#define IMU_ACCEL_XOUT_L 0x3C
#define IMU_ACCEL_YOUT_H 0x3D
#define IMU_ACCEL_YOUT_L 0x3E
#define IMU_ACCEL_ZOUT_H 0x3F
#define IMU_ACCEL_ZOUT_L 0x40
#define IMU_TEMP_OUT_H 0x41
#define IMU_TEMP_OUT_L 0x42
#define IMU_GYRO_XOUT_H 0x43
#define IMU_GYRO_XOUT_L 0x44
#define IMU_GYRO_YOUT_H 0x45
#define IMU_GYRO_YOUT_L 0x46
#define IMU_GYRO_ZOUT_H 0x47
#define IMU_GYRO_ZOUT_L 0x48
#define IMU_MOT_DETECT_STATUS 0x61
#define IMU_SIGNAL_PATH_RESET 0x68
#define IMU_MOT_DETECT_CTRL 0x69
#define IMU_USER_CTRL 0x6A
#define IMU_PWR_MGMT_1 0x6B
#define IMU_PWR_MGMT_2 0x6C
#define IMU_DMP_BANK 0x6D
#define IMU_DMP_RW_PNT 0x6E
#define IMU_DMP_REG 0x6F
#define IMU_DMP_REG_1 0x70
#define IMU_DMP_REG_2 0x71
#define IMU_FIFO_COUNTH 0x72
#define IMU_FIFO_COUNTL 0x73
#define IMU_FIFO_R_W 0x74
#define IMU_WHO_AM_I_MPU9250 0x75 // Should return 0x71
#define IMU_XA_OFFSET_H 0x77
#define IMU_XA_OFFSET_L 0x78
#define IMU_YA_OFFSET_H 0x7A
#define IMU_YA_OFFSET_L 0x7B
#define IMU_ZA_OFFSET_H 0x7D
#define IMU_ZA_OFFSET_L 0x7E

#endif // IMU_REGISTERS_H
