name: Build

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build.yml
      - stm32f446retx_flash.ld
      - startup_stm32f446xx.s
      - CMakeLists.txt
      - Drivers/**
      - Core/**
      - Src/**

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:   [ ubuntu, windows ]
        type: [ debug, release ]

    runs-on: ${{ matrix.os }}-${{ matrix.os == 'ubuntu' && 'latest' || '2025' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools for Linux
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi # cmake ninja-build

      - name: Install build tools Windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          winget install --accept-source-agreements --accept-package-agreements --disable-interactivity -e --id Arm.GnuArmEmbeddedToolchain
        # winget install --accept-source-agreements --accept-package-agreements --disable-interactivity -e --id Ninja-build.Ninja
        # winget install --accept-source-agreements --accept-package-agreements --disable-interactivity -e --id Kitware.CMake

      - name: Configure
        run: cmake -G Ninja -DCMAKE_BUILD_TYPE="${{ matrix.type }}"
        working-directory: FC_firmware

      - name: Build
        run: cmake --build .
        working-directory: FC_firmware

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: "firmware-${{ matrix.os }}-${{ matrix.type }}"
          path: FC_firmware/FC_firmware.bin
          if-no-files-found: error
